### PR TITLE
Add 🇷🇺 Russian translation

### PR DESCRIPTION
**Pull request by lex111**
сс @simsim0709

### CODE REVIEW

**Comment by simsim0709** [comment]
@lex111 
Could you fix conflicts, so that I can merge?

Thanks in advance.

**Comment by lex111** [comment]
What conflicts? GitHub does not show any conflicts.

**Comment by lex111** [comment]
I updated in accordance with the master, please accept the translation.

**Comment by simsim0709** [comment]
Thanks, @lex111 .

I thought there was a conflict. Sorry for that! 👍

**Comment by lex111** [comment]
Do not forget to update `gh-pages` branch, I suppose it needs to be automated?

**Comment by simsim0709** [comment]
Yop. Travis did it for us. 😄
You can check out here(https://learn-vuejs.github.io/vue-patterns/ru/)

**Pull request merged**
