### PR TITLE
translation into Chinese

### PR DESCRIPTION
**Pull request by ZYSzys**

### CODE REVIEW

**Comment by yoyoys** [comment]
我也做了一個繁體中文的翻譯，
https://github.com/yoyoys/vue-patterns-cht

**Comment by simsim0709** [comment]
Thanks, @ZYSzys and @yoyoys.

Nice works!

Do you guys want me to add the link to README or something else?

**Comment by ZYSzys** [comment]
@simsim0709 Good idea.And I'm gonna add this two links and create a new PR.

**Comment by yoyoys** [comment]
It's my pleasure.

**Pull request closed without merging**
